on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        if: startsWith(github.ref, 'refs/tags/v') && github.event.base_ref=='refs/heads/main'
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        if: startsWith(github.ref, 'refs/tags/v') && github.event.base_ref=='refs/heads/main'
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: startsWith(github.ref, 'refs/tags/v') && github.event.base_ref=='refs/heads/main'
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
